name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, toolbartender]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy on EC2 (self-hosted)
        run: |
          set -e
          
          cd ~
          source .toolbartender/bin/activate
          pip install -r ~/toolbartender-mcp/requirements.txt
          
          cd ~/toolbartender-mcp
          git fetch --all
          git reset --hard origin/main
          
          sudo systemctl restart toolbartender
          sudo systemctl status toolbartender --no-pager
      
    #   - name: Deploy on EC2 (self-hosted)
    #     uses: appleboy/ssh-action@v1.0.3
    #     with:
    #       host: ${{ secrets.EC2_HOST }}
    #       username: ${{ secrets.EC2_USER }}
    #       key: ${{ secrets.EC2_SSH_KEY }}
    #       debug: true
    #       timeout: 60s
    #       script: |
    #         set -e
    #         cd /opt/toolbartender-mcp
    #         git fetch --all
    #         git reset --hard origin/main
    #         source .venv/bin/activate
    #         pip install -r requirements.txt
    #         sudo systemctl restart toolbartender
    #         sudo systemctl status toolbartender --no-pager
